### ISSUE TITLE
when no errors, can not close quickfix

### ISSUE THREAD

**Issue by clllanqing** [darrikonn/vim-gofmt#1] opened 2021-05-21 09:40 UTC
```
  1   if l:err == 0
49      call go#list#Window(go#list#Type("GoFmt"), 0)   "to close quickfix
  1     call go#fmt#update_file(l:tmpname, a:withGoimport)
  2   elseif !go#config#FmtFailSilently()
  3     let errors = s:parse_errors(expand('%'), out)
  4     call s:show_errors(errors)
  5   endif
```

**Comment by darrikonn** [comment] 2021-06-01 19:57
Sorry for late answers.. this somehow went past me.

Could you further elaborate on the issue. Is this a bugfix (since I don't see the line you're referring to in the codebase)?

Would be helpful getting steps so I can reproduce this.
Thanks

**Comment by clllanqing** [comment] 2021-06-03 04:00
1. have error in my project
2. quickfix will open
3. fix error in my project
4. quickfix will not close!

https://github.com/darrikonn/vim-gofmt/blob/f2c442a5c8ae0acea65d4a73fb35537f6e9a928b/autoload/go/fmt.vim#L48

yes, i slove problem with this code
```
call go#list#Window(go#list#Type("GoFmt"), 0)
```

**Comment by darrikonn** [comment] 2021-06-03 10:10
Mmm I see :).. do you want to contribute and submit a PR with the fix?

**Comment by clllanqing** [comment] 2021-06-04 01:21
hah, you fix the bug

**Comment by darrikonn** [comment] 2021-06-04 09:03
Alright, will do :).

Fixed in: https://github.com/darrikonn/vim-gofmt/commit/8122cc921954c2ddb4b893558096b27e29e80a29

Thanks for submitting the issue!

**Closed as completed by darrikonn** 2021-06-04 09:03 UTC
